dist: bionic
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ppa:mhier/libboost-latest
    packages:
      - libboost1.70-dev
      - valgrind
      - cppcheck

jobs:
  include:
    - stage: build
      script: tools/travis/build.sh
    - stage: test
      script: tools/travis/test.sh
    - stage: lint
      script: tools/travis/lint.sh
