dist: bionic
language: cpp

before_install:
  - sudo add-apt-repository ppa:mhier/libboost-latest -y
  - sudo apt-get update -q
  - sudo apt-get -y install clang clang-tidy libasio-dev libboost1.70-dev valgrind

jobs:
  include:
    - stage: build
      script: tools/travis/build.sh
    - stage: test
      script: tools/travis/test.sh
