dist: bionic
language: cpp

before_install:
  - sudo apt-get update -q
  - sudo apt-get -y install cmake clang clang-tidy valgrind libboost-date-time-dev libsdl2-dev

jobs:
  include:
    - stage: build
      script: tools/travis/build.sh
    - stage: test
      script: tools/travis/test.sh
