dist: bionic
sudo: false
language: cpp

addons:
  apt:
    packages:
      - libboost-system-dev
      - valgrind
      - cppcheck

jobs:
  include:
    - stage: build
      script: tools/travis/build.sh
    - stage: test
      script: tools/travis/test.sh
    - stage: lint
      script: tools/travis/lint.sh
