dist: bionic
language: cpp

before_install:
  - sudo apt-get update -q
  - sudo apt-get -y install clang clang-tidy libasio-dev libboost-date-time-dev valgrind

jobs:
  include:
    - stage: build
      script: tools/travis/build.sh
    - stage: test
      script: tools/travis/test.sh
