#!/bin/bash

set -e

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DIR_RELEASE="$DIR/../build_release"
DIR_DEBUG="$DIR/../build_debug"
DIR_TEST="$DIR/../build_test"
DIR_ECLIPSE="$DIR/../eclipse"

case $1 in
  'all')
    mkdir -p "$DIR_RELEASE"
    pushd "$DIR_RELEASE"
    cmake ../gameserver -DCMAKE_BUILD_TYPE=release
    ln -s ../data data
    popd

    mkdir -p "$DIR_DEBUG"
    pushd "$DIR_DEBUG"
    cmake ../gameserver -DCMAKE_BUILD_TYPE=debug
    ln -s ../data data
    popd

    mkdir -p "$DIR_TEST"
    pushd "$DIR_TEST"
    cmake ../gameserver -DCMAKE_BUILD_TYPE=debug -Dunittest=ON
    popd

    mkdir -p "$DIR_ECLIPSE"
    pushd "$DIR_ECLIPSE"
    cmake ../gameserver -G"Eclipse CDT4 - Unix Makefiles" -DCMAKE_BUILD_TYPE=debug -DCMAKE_ECLIPSE_VERSION=4.7.2 -DCMAKE_CXX_COMPILER_ARG1=-std=c++14
    ln -s ../data data
    popd
    ;;

  'release')
    mkdir -p "$DIR_RELEASE"
    pushd "$DIR_RELEASE"
    cmake ../gameserver -DCMAKE_BUILD_TYPE=release
    ln -s ../data data
    popd
    ;;

  'debug')
    mkdir -p "$DIR_DEBUG"
    pushd "$DIR_DEBUG"
    cmake ../gameserver -DCMAKE_BUILD_TYPE=debug
    ln -s ../data data
    popd
    ;;

  'test')
    mkdir -p "$DIR_TEST"
    pushd "$DIR_TEST"
    cmake ../gameserver -DCMAKE_BUILD_TYPE=debug -Dunittest=ON
    popd
    ;;

  'eclipse')
    mkdir -p "$DIR_ECLIPSE"
    pushd "$DIR_ECLIPSE"
    cmake ../gameserver -G"Eclipse CDT4 - Unix Makefiles" -DCMAKE_BUILD_TYPE=debug -DCMAKE_ECLIPSE_VERSION=4.7.2 -DCMAKE_CXX_COMPILER_ARG1=-std=c++14
    ln -s ../data data
    popd
    ;;

  'clean')
    rm -rf "$DIR_RELEASE" "$DIR_DEBUG" "$DIR_TEST" "$DIR_ECLIPSE"
    ;;

  *)
    echo "Usage: $0 [all | release | debug | test | eclipse | clean]"
    ;;
esac
