#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
DIR_RELEASE="$DIR/../build_release"
DIR_DEBUG="$DIR/../build_debug"
DIR_TEST="$DIR/../build_test"

case $1 in
  'all')
    mkdir -p "$DIR_RELEASE"
    pushd "$DIR_RELEASE"
    cmake ../gameserver -DCMAKE_BUILD_TYPE=release || exit 1
    popd

    mkdir -p "$DIR_DEBUG"
    pushd "$DIR_DEBUG"
    cmake ../gameserver -DCMAKE_BUILD_TYPE=debug || exit 1
    popd

    mkdir -p "$DIR_TEST"
    pushd "$DIR_TEST"
    cmake ../gameserver -DCMAKE_BUILD_TYPE=debug -Dunittest=ON || exit 1
    popd
    ;;

  'release')
    mkdir -p "$DIR_RELEASE"
    pushd "$DIR_RELEASE"
    cmake ../gameserver -DCMAKE_BUILD_TYPE=release || exit 1
    popd
    ;;

  'debug')
    mkdir -p "$DIR_DEBUG"
    pushd "$DIR_DEBUG"
    cmake ../gameserver -DCMAKE_BUILD_TYPE=debug || exit 1
    ;;

  'test')
    mkdir -p "$DIR_TEST"
    pushd "$DIR_TEST"
    cmake ../gameserver -DCMAKE_BUILD_TYPE=debug -Dunittest=ON || exit 1
    popd
    ;;

  *)
    echo "Usage: $0 [all | release | debug | test]"
    ;;
esac
