FROM debian:bullseye

WORKDIR /gameserver
COPY tools/docker/entrypoint_run.sh /gameserver/
COPY docker_build/bin/worldserver /gameserver/
COPY docker_build/bin/loginserver /gameserver/
COPY docker_build/data /gameserver/data/
ENTRYPOINT ["/gameserver/entrypoint_run.sh"]
