FROM debian:bullseye

RUN apt-get update && \
    apt-get install -y acl git cmake clang-9 libboost-date-time-dev && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /
COPY build_entrypoint.sh /
ENTRYPOINT ["/build_entrypoint.sh"]
