FROM debian:bullseye

RUN apt-get update && \
    apt-get install -y build-essential acl git cmake clang-9 libboost-date-time-dev && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /
COPY tools/docker/entrypoint_build.sh /
ENTRYPOINT ["/entrypoint_build.sh"]
